# The amount of time between Swaps in seconds. (Default is 300 seconds (5 minutes)
# Default: 300
swapInterval: 300

# The amount of time that the swap interval can vary +/- in seconds. (Default is 120 seconds (2 minutes) This means that default swap time is between 3 and 7 minutes.
# If you don't want the interval to vary set this to 0.
# Default: 120
swapIntervalVariation: 120

# The amount of time in seconds that no swap is allowed to occur.
# The first swap will be scheduled after this time so assuming default settings the first swap would happen after 8 - 12 minutes.
# If you don't want a Grace Period set this to 0.
# Default: 300
gracePeriod: 300

# Should Participating Players be able to attack each other?
# Default: false
allowPvp: false

# Should travel to the Nether be completely disabled?
# You may want to disable this as if a Player reaches the Nether very quickly it's effectively a Checkmate as there's very few ways to survive.
# Par Exemple: https://youtu.be/vXS1pXWslxs?t=937
# Default: true
allowNether: true

# Allow Players to avoid Swapping by Pearling just before the Swap occurs?
# This will only affect pearls thrown prior to a swap.
# Default: true
allowPearlSkipping: true

# The amount of Hostile mobs which will be allowed to spawn.
# This allows you to limit the amount of threats from Mobs so that deaths are a result
# of other Players.
# 100% - All mobs will spawn as usual.
# 50% - Only half as many Mobs.
# 0% - Mobs will not spawn.
# etc.
# Default: 100
mobSpawnRate: 100

# Should we display a Timer at the Top of each Players showing how long is left until the Next Swap?
# Default: false
showTimer: false

# Should we report Debug information to all online operators?
# You might want to keep this disabled.
# Default: false
debugMode: false