name: Deathswap
version: ${project.version}
main: com.wilkei.deathswap.Deathswap
api-version: 1.17
authors: [ Wilkei ]
commands:
  deathswap:
    usage: §cInvalid Command Usage! Please use §e/deathswap help§c for a list of Commands.