name: Deathswap
version: ${project.version}
main: DeathswapPlugin
api-version: 1.17
authors: [ Wilkai ]
commands:
  deathswap:
    usage: §cInvalid Command Usage! Please use §e/deathswap help§c for a list of Commands.
    aliases:
      - ds
    description: Command used for controlling all aspects of Deathswap.